### ISSUE TITLE
Add support for propane level sensor (iGrillv3)

### ISSUE THREAD

**Issue by eth0up** [1mckenna/esp32_iGrill#9]
My iGrillv3 is equipped with a propane level sensor. The official iGrill app reports the propane level. I'm submitting this issue as a feature request to see the same level reporting functionality within esp32_iGrill. 

- Propane Level sensor's BLEUUID is `f5d40001-3548-4c22-9947-f3673fce3cd9s`
- Propane Level sensor has 5 possible values: `100, 75, 50, 25, or 0`
- (Python) the maths used to format the reported level's value: `float(bytearray(self.propane_level.read())[0])*25`
- Implementation in Python, for reference: https://github.com/bendikwa/igrill/pull/24/commits/e6522bf0328554fafbcbc38433d91a491248cd7c

**Comment by 1mckenna** [comment]
I just pushed an updated version to the propane branch that should work (or be close). Can you switch to that branch and then try that version and let me know the results.

**Comment by eth0up** [comment]
> 
> 
> I just pushed an updated version to the propane branch that should work (or be close). Can you switch to that branch and then try that version and let me know the results.

Line #288 in `esp32_iGrill.ino` needs a trailing semicolon for successful compilation in Arduino IDE: https://github.com/1mckenna/esp32_iGrill/blob/dce5b6529a832fe31ee3a79143d82a15ddf46fe6/esp32_iGrill.ino#L288

I uploaded the propane branch sketch to my esp32, but unfortunately I'm not seeing a propane sensor within Home Assistant or MQTT Explorer. I'm attempting to revive my laptop so that I can view the esp logs while being simultaneously within bluetooth range of the igrill (the desktop pc I'm using is not within bt range) . Hopefully the debug output while connected gives us some hints for needed changes. It might be worth noting that my propane tank is currently less than 25% full, so the reported value would be expected as "0".

Thanks for getting started on this enhancement so swiftly!

**Comment by 1mckenna** [comment]
I made a small update to show if a propane sensor was setup in the systeminfo mqtt topic. Can you try the latest and let me know if in MQTT its showing propane sensor as true or false.

**Comment by eth0up** [comment]
> 
> 
> I made a small update to show if a propane sensor was setup in the systeminfo mqtt topic. Can you try the latest and let me know if in MQTT its showing propane sensor as true or false.

MQTT is showing the following for propane sensor:
` "Propane Sensor": "0"`

I'm on software:
`"sw_version": "1.10-000"`

**Comment by 1mckenna** [comment]
Looks like it's not detecting that characteristic. 

Can you perform the steps below and attach a screenshot of the output here.
1. Install the Weber iGrill App and pair the device to the phone via the app
2. Install the nrfConnect Android App
3. Once in the App Click on the Bonded Tab
4. You should see your iGrill listed, click Connect
5. It should then go through discovery of the services
6. In the listed services can you find the one related to propane level and take a screenshot/attach all the details shown.

**Comment by eth0up** [comment]
Here's what I've got from the nrfConnect app:
![nrfConnect_igrill_propane](https://user-images.githubusercontent.com/14995689/129830384-a9e79f5b-cc9f-4619-a84e-c21536239ceb.jpeg)


Value `0x030000` matches up with 75% fuel level as identified on this git comment:
https://github.com/bendikwa/igrill/issues/12#issuecomment-699583380

Let me know whether there's anything else you'd like me to test. Thanks!

**Comment by 1mckenna** [comment]
Looks like the propane level is on its own service uuid which is why we weren't able to read that characteristic. I just pushed changes that hopefully should get us some values back. When you get a bit of free time can you pull the latest code and let me know the results.

**Comment by eth0up** [comment]
I synced with latest, unfortunately I'm still not seeing the propane sensor in Home Assistant. MQTT Explorer reports `"Propane Sensor": "0"`. 

To double check, I connected via the Weber iGrill App and confirmed that propane level displays as expected:
![weberapp_igrill_propane](https://user-images.githubusercontent.com/14995689/130004727-e8d7fd16-2e95-4dca-b244-9103113b8ef1.jpeg)

**Comment by 1mckenna** [comment]
Oops realized after you replied that I forgot to change the UUID for the Propane service when I made the updates. Can you re-pull and try again.

**Comment by eth0up** [comment]
> 
> 
> Oops realized after you replied that I forgot to change the UUID for the Propane service when I made the updates. Can you re-pull and try again.

MQTT Explorer reports `"Propane Sensor": "0"` after applying the latest change. I confirmed that the app is still displaying the propane level.

**Comment by 1mckenna** [comment]
Just to confirm you unpaired your phone from the iGrill before testing?

In your latest test is it still reporting the temps to mqtt?

Did you happen to get your laptop running so we can get the debug logs for a closer look at what's happening? If not I'll need to make some updates to throw the debug logs to mqtt.

**Comment by eth0up** [comment]
> 
> 
> Just to confirm you unpaired your phone from the iGrill before testing?
> 
> In your latest test is it still reporting the temps to mqtt?
> 
> Did you happen to get your laptop running so we can get the debug logs for a closer look at what's happening? If not I'll need to make some updates to throw the debug logs to mqtt.

I did unpair from my phone before re-testing with esp32. In latest, I was still seeing temperatures and battery reported to MQTT. I also tried forcing `has_propane_sensor=true` but did not see any MQTT output related to propane sensor. 

I just finished getting my laptop up and running and confirmed that I can see the serial monitor output from esp32 as it runs iGrill code.

**Comment by 1mckenna** [comment]
I just changed how the code is trying to detect if the propane service exists and added in some additional logging. Can you try pulling the most recent and then let me know if its showing in the Serial logs if it detects the propane service or not.

**Comment by eth0up** [comment]
After pulling latest the serial logs show that the esp32 successfully connects to the propane service and accurately displays the propane level value - very awesome!
![image](https://user-images.githubusercontent.com/14995689/130512037-fe9b8b31-dedd-4908-8fff-5ab749b6f622.png)

I'm also seeing messages in MQTT Explorer reporting the propane_level.

**Comment by 1mckenna** [comment]
Awesome!! Are you also running Home Assistant? If so after a restart of HA did the propane level sensor show up properly there too?

**Comment by eth0up** [comment]
> 
> 
> Awesome!! Are you also running Home Assistant? If so after a restart of HA did the propane level sensor show up properly there too?

I am running HA, but the propane sensor does not show up under the igrill device or in the entities. I noticed that the MQTT messages for Battery and Probe (which both show up in HA as sensors under the igrill device) are formatted differently than the propane_level:
![image](https://user-images.githubusercontent.com/14995689/130525403-6267a34e-d777-4588-ba57-7e9c33bc22b7.png)

While propane level is accurately reported  in the serial output, it seems that the same value isn't being sent via MQTT.

**Comment by 1mckenna** [comment]
I just pushed an update that should hopefully fix that issue. You'll likely need to delete the topics via MQTT explorer for things to show up properly. Then if all looks well in MQTT Explorer a restart of HA should get the propane level sensor discovered.

**Comment by eth0up** [comment]
After latest update, a propane sensor shows up under the igrill device in HA! The value was reported as "3%", which led me to believe the code for reporting value was missing a multiplication operation.

On my local copy I found and changed [Line#391](https://github.com/1mckenna/esp32_iGrill/commit/9cb7be0a80dd8acbf19ef1e5dd6ff47bd3839200#L391) from `publishPropaneLevel(value);` to `publishPropaneLevel(value*25);` and re-uploaded to the esp32. After this small change Home Assistant now reports a propane sensor with value of 75, which matches my current propane level.

**Comment by 1mckenna** [comment]
Thank you! I just fixed and pushed that change. If everything else is working well I'll go ahead and push this to the main branch.

**Comment by eth0up** [comment]
> 
> 
> Thank you! I just fixed and pushed that change. If everything else is working well I'll go ahead and push this to the main branch.

For good measure I pulled latest and uploaded to the esp32 - it's working very well! Thanks for spending your time and effort to get this feature added.

**Comment by 1mckenna** [comment]
I just merged this into the main branch and added you to the contributions section in the readme.  Thanks again for the help getting this working and tested.
